# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ba70c7f0f57a7dbfc4c966c83b52a903eb7682a9d23776205daac3bfcd2c50395661fea06ea13a388c6d9661113211ea5617f7c4ee5c88f28a1f6b37010ed0f

test:
  secret_key_base: 71970793b76320577390dd13ec804cbaaf20bb32219bf17e3f76591cfdc9f32747bfc6b555d2ad551a34018820c4a75f5d9841ef1ccd3b2965c8948377d88985

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
